### ISSUE TITLE
Sending buttonTemplates appeared as it was sent to me from target on phone

### ISSUE THREAD

**Issue by ariona** [wppconnect-team/wa-js#905]
## Description

When sending templateButtons to a target, it was successfully sent and looks okay on WAWeb.
But when viewed on my phone, _it appeared as it was sent by target to me_. but on target phone it was sent from me (correct view)
While this working, but it confuse me as it's like the target sending me the message

## Environment

- **WhatsApp version:** 2.2305.7
- **WA-JS version(s):** 2.19.0
- **Browser:** Chrome 109.0.5414.119 (Official Build) (x86_64)
- **OS:** Monterey 12.6.2 
- **MultiDevice (BETA):** yes

## Steps to Reproduce

1. Send templateButtons message to target
2. Open your WhatsApp on your phone, and view target chat
3. The template button sent from target, not user

## Your Code

```js
WPP.chat.sendTextMessage('6287824602500@c.us','Testing URL/Phone Button', {
  useTemplateButtons: true,
  buttons: [
    {
        url: "https://google.com/",
        text: "Google Site"
    },
    {
        phoneNumber: "+628888888888",
        text: "Call me"
    },
    {
        id: "your custom id 1",
        text: "Some text"
    },

  ],
  title: "Title text",
  footer: "Footer text"
})
```

## Additional context / Screenshot
![WhatsApp Image 2023-02-05 at 5 58 18 PM](https://user-images.githubusercontent.com/752483/216815063-75ad2346-0182-4f71-b450-4e267d5f55da.jpeg)

templateButtons message appeared as if target sent the message, not me

**Comment by edgardmessias** [comment]
Yes, this is a BUG on WhatsApp app, not in WA-JS

**Comment by macleysousa** [comment]
> Yes, this is a BUG on WhatsApp app, not in WA-JS

I found a branch of Baileys is sending the buttons [https://github.com/Auties00/Baileys](url)

``` js
const buttons = [
  {buttonId: 'id1', buttonText: {displayText: 'Button 1'}, type: 1},
  {buttonId: 'id2', buttonText: {displayText: 'Button 2'}, type: 1},
  {buttonId: 'id3', buttonText: {displayText: 'Button 3'}, type: 1}
]

const buttonMessage = {
    text: "Hi it's button message",
    footer: 'Hello World',
    buttons: buttons,
    headerType: 1
}

const sendMsg = await sock.sendMessage(id, buttonMessage)
```

so I believe that it is still possible to send buttons, we just have to describe the correct template. I'm trying to do reserse engineering to find out, but I haven't been successful yet

**Comment by edgardmessias** [comment]
@macleysousa There two ways to send the buttons: replyButtons (only buttons) and templateButtons (with call/url). I fixed on the latest release of WA-JS to work with replyButtons, but there are no anything to do with templateButtons at moment.
Note: If you are using business account, the Meta is blocking the send.

@macleysousa Existem duas maneiras de enviar os botões: replyButtons (somente botões) e templateButtons (com chamada/url). Corrigi a versão mais recente do WA-JS para trabalhar com os botões de resposta, mas não há nada a se fazer com os templateButtons no momento.
Nota: Se você estiver usando uma conta business, o Meta está bloqueando o envio.

Aproveite, entre no nosso discord, a maioria é do Brasil no WPPConnect.

**Comment by macleysousa** [comment]
@edgardmessias  mudou alguma coisa em como é criado o botão? Porque atualizei para a versão mas recente e ainda não estou conseguindo enviar os botões de  **replyButtons** 

@edgardmessias change anything in how the button is created? Because I updated to the latest version and I still can't send the **replyButtons** buttons

**Comment by raajrush** [comment]
Forget about buttons now, it will not longer available anywhere expect official WhatsApp api

**Comment by edgardmessias** [comment]
The buttons are deprecated, the Meta blocked it

**Comment by Parveen-Mothsara** [comment]
Hi @edgardmessias ,
How to send text message on unknown number,because when we try to send using  SendTextMessage getting chat not exist

**Comment by yogithesymbian** [comment]
so we cant send a button ?

**Comment by jaydeep9246** [comment]
someone can send image + button, I received it on my number , but that message cant show in web WhatsApp, anyone know which method they use to send button?
